### ISSUE TITLE
i386 and armel build failures on debian sid since ~1.2.17

### ISSUE THREAD

**Issue by snd1** [lsp-plugins/lsp-plugins#511]
Since version ~1.2.17 the architectures i386 and armel fail to build lsp-plugins. Are these architectures not anymore supported? Or can this be *easily* fixed?

Armel build failure:
```
mkdir -p /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/specific/
g++ -o /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/specific/LedMeterChannel.o -c main/widgets/specific/LedMeterChannel.cpp -fPIC -g -O2 -ffile-prefix-map=/build/reproducible-path/lsp-plugins-1.2.21=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_TIME_BITS=64 -Wdate-time -D_FORTIFY_SOURCE=2 -march=armv5t -marm -O2 -fvisibility=hidden -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall -DLSP_TK_LIB_BUILTIN -fvisibility=hidden -DUSE_LSP_COMMON_LIB -DUSE_LSP_LLTL_LIB -DUSE_LSP_R3D_IFACE -DUSE_LSP_RUNTIME_LIB -DUSE_LSP_DSP_LIB -DUSE_LSP_WS_LIB -DUSE_LIBCAIRO -DUSE_LIBDL -DUSE_LIBFONTCONFIG -DUSE_LIBFREETYPE -DUSE_LIBPTHREAD -DUSE_LIBRT -DUSE_LIBSNDFILE -DUSE_LIBX11 -DUSE_LIBXRANDR   -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-lltl-lib/include" -DLSP_LLTL_LIB_BUILTIN -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-r3d-iface/include" -DLSP_R3D_IFACE_BUILTIN -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-runtime-lib/include" -DLSP_RUNTIME_LIB_BUILTIN -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-dsp-lib/include" -DLSP_DSP_LIB_BUILTIN -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-ws-lib/include" -DLSP_WS_LIB_BUILTIN -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/pixman-1   -I/usr/include/freetype2 -I/usr/include/libpng16  -I/usr/include/freetype2 -I/usr/include/libpng16    -I/usr/include/opus -I/usr/include/arm-linux-gnueabi    -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-tk-lib/include" -DLSP_TK_LIB_BUILTIN -MMD -MP -MF /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/specific/LedMeterChannel.d -MT /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/specific/LedMeterChannel.o
  ld   [lsp-tk-lib] lsp-tk-lib.o
ld -o /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/lsp-tk-lib.o -r  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/helpers/arrange.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/helpers/draw.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/helpers/graphics.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/helpers/keyboard.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/helpers/mime.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/Listener.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/base/BitEnum.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/base/Enum.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/base/Flags.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/base/MultiProperty.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/base/Property.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/base/Ptr.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/base/SimpleProperty.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/collection/CollectionListener.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/collection/ColorRanges.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/collection/FileFilters.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/collection/FloatArray.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/collection/StringList.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/collection/WidgetList.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/collection/WidgetSet.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/BorderStyle.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/ButtonMode.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/DrawMode.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/FileDialogMode.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/GraphFrameFunction.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/IndicatorType.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/MenuItemType.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/Orientation.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/Pointer.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/Scrolling.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/TextAdjust.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/enum/WindowPolicy.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/flags/Allocation.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/flags/WindowActions.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Alignment.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Arrangement.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Color.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/ColorRange.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Embedding.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/FileMask.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Font.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Layout.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Padding.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Point2D.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Position.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/RangeFloat.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Rectangle.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Shortcut.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Size.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/SizeConstraints.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/SizeRange.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/StepFloat.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/TextFitness.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/TextLayout.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/TextSelection.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/multi/Vector2D.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/simple/Boolean.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/simple/Float.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/simple/Integer.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/simple/PathPattern.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/simple/String.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/specific/GraphFrameData.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/prop/specific/GraphMeshData.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/style/BuiltinStyle.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/style/IStyleFactory.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/style/IStyleListener.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/style/Schema.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/style/Style.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/style/StyleSheet.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/sys/Atoms.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/sys/Display.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/sys/Shortcuts.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/sys/Slot.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/sys/SlotSet.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/sys/Timer.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/sys/settings.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/tk.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/util/KeyboardHandler.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/util/ShortcutTracker.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/util/TextCursor.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/util/TextDataSink.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/util/TextDataSource.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/util/URLSink.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/3d/Area3D.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/base/Registry.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/base/Widget.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/base/WidgetContainer.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/compound/ComboBox.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/compound/ComboGroup.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/compound/ListBox.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/compound/Menu.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/containers/Align.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/containers/Box.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/containers/Grid.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/containers/Group.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/containers/MultiLabel.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/containers/PopupWindow.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/containers/ScrollArea.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/containers/Tab.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/containers/TabControl.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/containers/TabGroup.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/containers/Window.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/dialogs/FileDialog.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/dialogs/MessageBox.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/graph/Graph.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/graph/GraphAxis.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/graph/GraphDot.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/graph/GraphFrameBuffer.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/graph/GraphItem.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/graph/GraphLineSegment.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/graph/GraphMarker.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/graph/GraphMesh.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/graph/GraphOrigin.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/graph/GraphText.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/Bevel.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/Button.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/CheckBox.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/Edit.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/Fader.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/Hyperlink.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/Indicator.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/Knob.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/Label.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/Led.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/ListBoxItem.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/MenuItem.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/ProgressBar.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/RadioButton.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/ScrollBar.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/Separator.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/TabItem.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/simple/Void.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/specific/AudioChannel.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/specific/AudioSample.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/specific/FileButton.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/specific/Fraction.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/specific/LedMeter.o  /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-tk-lib/main/widgets/specific/LedMeterChannel.o 
make[6]: Leaving directory '/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-tk-lib/src'
make[5]: Leaving directory '/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-tk-lib'
make[4]: Leaving directory '/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-plugin-fw/src'
make[3]: *** [Makefile:67: all] Error 2
make[3]: Leaving directory '/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-plugin-fw'
make[2]: *** [Makefile:145: all] Error 2
make[2]: Leaving directory '/build/reproducible-path/lsp-plugins-1.2.21/src'
make[1]: *** [Makefile:68: all] Error 2
make[1]: Leaving directory '/build/reproducible-path/lsp-plugins-1.2.21'
dh_auto_build: error: make -j8 "INSTALL=install --strip-program=true" returned exit code 2
make: *** [debian/rules:45: binary-arch] Error 25
```
Armel full build log: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=armel&ver=1.2.21-2&stamp=1744323541&raw=0

i386 build failure:
```
  compressing file: /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-plugin-fw/res/ui/util/surge_filter.xml
  compressing file: /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-plugin-fw/res/ui/utils/referencer.xml
  compressing file: /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-plugin-fw/res/ui/window.xml
Input size: 3235115, compressed size: 756175, compression ratio: 4.28
Execution time: 8.66 s
g++ -o /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-plugin-fw/lsp-plugin-fw-ui-res.o -c /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-plugin-fw/lsp-plugin-fw-ui-res.cpp -fPIC -g -O2 -ffile-prefix-map=/build/reproducible-path/lsp-plugins-1.2.21=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -march=i586 -m32 -O2 -fvisibility=hidden -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall -DLSP_INSTALL_PREFIX=\"/usr\" -DUSE_LIBCAIRO -DUSE_LIBDL -DUSE_LIBFONTCONFIG -DUSE_LIBFREETYPE -DUSE_LIBGL -DUSE_LIBJACK -DUSE_LIBPTHREAD -DUSE_LIBRT -DUSE_LIBSNDFILE -DUSE_LIBX11 -DUSE_LIBXRANDR -DUSE_LSP_3RD_PARTY -DUSE_LSP_COMMON_LIB -DUSE_LSP_DSP_LIB -DUSE_LSP_DSP_UNITS -DUSE_LSP_LLTL_LIB -DUSE_LSP_PLUGINS_SHARED -DUSE_LSP_PLUGIN_FW -DUSE_LSP_R3D_BASE_LIB -DUSE_LSP_R3D_IFACE -DUSE_LSP_RUNTIME_LIB -DUSE_LSP_TK_LIB -DUSE_LSP_WS_LIB     -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/pixman-1     -I/usr/include/freetype2 -I/usr/include/libpng16   -I/usr/include/freetype2 -I/usr/include/libpng16           -I/usr/include/opus -I/usr/include/i386-linux-gnu       -idirafter "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-3rd-party/include"  -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN  -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-dsp-lib/include" -DLSP_DSP_LIB_BUILTIN  -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-dsp-units/include" -DLSP_DSP_UNITS_BUILTIN  -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-lltl-lib/include" -DLSP_LLTL_LIB_BUILTIN  -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-plugins-shared/include" -DLSP_PLUGINS_SHARED_BUILTIN -DLSP_PLUGINS_SHARED_PUBLISHER  -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-plugin-fw/include" -DLSP_PLUGIN_FW_BUILTIN  -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-r3d-base-lib/include" -DLSP_R3D_BASE_LIB_BUILTIN  -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-r3d-iface/include" -DLSP_R3D_IFACE_BUILTIN  -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-runtime-lib/include" -DLSP_RUNTIME_LIB_BUILTIN  -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-tk-lib/include" -DLSP_TK_LIB_BUILTIN  -I "/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-ws-lib/include" -DLSP_WS_LIB_BUILTIN  -DWITH_CLAP_FEATURE  -DWITH_JACK_FEATURE  -DWITH_LADSPA_FEATURE  -DWITH_LV2_FEATURE  -DWITH_UI_FEATURE  -DWITH_VST2_FEATURE  -DWITH_VST3_FEATURE  -DWITH_XDG_FEATURE -MMD -MP -MF /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-plugin-fw/lsp-plugin-fw-ui-res.d -MT /build/reproducible-path/lsp-plugins-1.2.21/.build/target/lsp-plugin-fw/lsp-plugin-fw-ui-res.o
make[4]: Leaving directory '/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-plugin-fw/src'
make[3]: *** [Makefile:67: all] Error 2
make[3]: Leaving directory '/build/reproducible-path/lsp-plugins-1.2.21/modules/lsp-plugin-fw'
make[2]: *** [Makefile:145: all] Error 2
make[2]: Leaving directory '/build/reproducible-path/lsp-plugins-1.2.21/src'
make[1]: *** [Makefile:68: all] Error 2
make[1]: Leaving directory '/build/reproducible-path/lsp-plugins-1.2.21'
dh_auto_build: error: make -j6 "INSTALL=install --strip-program=true" returned exit code 2
make: *** [debian/rules:45: binary-arch] Error 25
```
i386 full build log: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=i386&ver=1.2.21-2&stamp=1744323531&raw=0

**Comment by sadko4u** [comment]
OK, got the information, will try to reproduce and fix ASAP.

**Comment by sadko4u** [comment]
Hi @snd1 

These patches should fix the armv5t build:

https://github.com/lsp-plugins/lsp-common-lib/commit/cb172e3c0e8497577018b6055fb4edefe9aae386
https://github.com/lsp-plugins/lsp-common-lib/commit/f66fc88adc4c743ed019aef8f173801aa1df5053
https://github.com/lsp-plugins/lsp-common-lib/commit/b1fec83daf8aa2b28962e1eb0502ac9ac6215b3b

This patch should fix the i386 build:

https://github.com/lsp-plugins/lsp-common-lib/commit/cafb2fbf22f32193178e39de3c34b3caf37cc353

Please try and let me know if you meet some problems.

**Comment by snd1** [comment]
Hi @sadko4u Thanks a lot, this works! https://buildd.debian.org/status/package.php?p=lsp-plugins

**Comment by sadko4u** [comment]
@snd1 I also see that for [hurd-amd64](https://buildd.debian.org/status/architecture.php?a=hurd-amd64&suite=sid) build scripts can not detect the build platform and thus tries to build with macro definitions for MacOS.

I could try to fix platform detection if you provide the output of these commands for the following commands:
```
uname -s
uname -m
echo | g++ -dM -E -x c++ -
```

**Comment by snd1** [comment]
Thanks for the offer, but i think this will be complicated.
First of all this is no official arch of debian and it is not linux, it is hurd. so according to the build failure `fatal error: xlocale.h: No such file or directory`... Full build log you can see here https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=hurd-amd64&ver=1.2.21-3&stamp=1744452772&raw=0
Aso i have no debian hurd-amd64 machine here and the current image does not boot in qemu, so i can not help much with it. Maybe we can look at this later. Thanks again.

**Comment by snd1** [comment]
Seems like there is still a problem with armel, at least the jack bins seems to fail in CI test: https://ci.debian.net/packages/l/lsp-plugins/testing/armel/59823464/ ... i will try to reproduce this later today

**Comment by snd1** [comment]
the CI only tests the jack bin with the -h flag

**Comment by sadko4u** [comment]
The log is very unclear.
There is no information about plugin being executed nor the instruction/function caused the crash. Is there any way to reproduce the problem manually?

**Comment by sadko4u** [comment]
Whoops, it seems that plugin is executed with the `-h` or `--help` flag.
Isn't it related to this problem?
https://github.com/lsp-plugins/lsp-plugins/issues/506

**Comment by sadko4u** [comment]
Try this patch:
https://github.com/lsp-plugins/lsp-plugin-fw/commit/3c1b3b2d4b3518eb030473fbeefb76e9c3f63a23

**Comment by snd1** [comment]
The other archs don't have this problem, only armel. The patch is already part of the package: https://salsa.debian.org/multimedia-team/lsp-plugins/-/blob/master/debian/patches/1004-Fix_segfault_with_jack_plugins.patch?ref_type=heads

But yeah, i try to get more information for this, by reproduce it later.

**Comment by sadko4u** [comment]
> when i will find a solution for testing armel properly, i will let you know

I think it is a good reason to open new ticket then. This ticket will be closed when 1.2.22 will be released.

**Comment by sadko4u** [comment]
Fixed in 1.2.22!
